import {AddableComponents} from '../types/addableComponents'

/**
 * List of components that can be added to the form
 */
const addableComponents : AddableComponents[] = [

    {
        "visibleIf": null,
        "permissionContexts": null,
        "name": null,
        "type": "html",
        "title": "Otsikko",
        "required": null,
        "contexts": [],
        "flags": null,
        "placeholder": null,
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": null,
        "sourceUrl": null,
        "uploadUrl": null,
        "singleFile": null,
        "onlyImages": null,
        "maxFileSize": null,
        "addRows": null,
        "draggable": null,
        "columns": [],
        "src": null,
        "text": null,
        "html": "<h1>Väliotsikko</h1>"
      },
      {
        "visibleIf": null,
        "permissionContexts": null,
        "name": null,
        "type": "html",
        "title": "Tekstikenttä",
        "required": null,
        "contexts": [],
        "flags": null,
        "placeholder": null,
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": null,
        "sourceUrl": null,
        "uploadUrl": null,
        "singleFile": null,
        "onlyImages": null,
        "maxFileSize": null,
        "addRows": null,
        "draggable": null,
        "columns": [],
        "src": null,
        "text": null,
        "html": "<p>Tekstikenttä</p>"
      },
      {
        "visibleIf": null,
        "permissionContexts": null,
        "name": "",
        "type": "text",
        "title": "Muokattava teksti",
        "required": null,
        "contexts": [],
        "flags": null,
        "placeholder": "Esimerkkiteksti",
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": [],
        "sourceUrl": null,
        "uploadUrl": null,
        "singleFile": null,
        "onlyImages": null,
        "maxFileSize": null,
        "addRows": null,
        "draggable": null,
        "columns": [],
        "src": null,
        "text": null,
        "html": null
      },
      {
        "visibleIf": null,
        "permissionContexts": null,
        "name": "status",
        "type": "radio",
        "title": "Valintanappula",//Tila
        "required": null,
        "contexts": [],
        "flags": {
          "managementEditable": true
        },
        "placeholder": null,
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": [
          {
            "name": null,
            "text": null,
            "checked": true,
            "selected": null
          }
        ]
      },
      {
        "visibleIf": null,
        "permissionContexts": null,
        "name": null,
        "type": "select",
        "title": "Alasvetovalikko",
        "required": null,
        "contexts": [],
        "flags": null,
        "placeholder": null,
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": [],
        "sourceUrl": null,
        "uploadUrl": null,
        "singleFile": null,
        "onlyImages": null,
        "maxFileSize": null,
        "addRows": null,
        "draggable": null,
        "columns": [],
        "src": null,
        "text": null,
        "html": null
      },
      {
        "visibleIf": null,
        "permissionContexts": null,
        "name": null,
        "type": "checklist",
        "title": "Valintaruutu",
        "required": null,
        "contexts": [],
        "flags": null,
        "placeholder": null,
        "_class": null,
        "readonly": null,
        "help": null,
        "_default": null,
        "min": null,
        "max": null,
        "step": null,
        "checked": null,
        "printable": null,
        "options": null,
        "sourceUrl": null,
        "uploadUrl": null,
        "singleFile": null,
        "onlyImages": null,
        "maxFileSize": null,
        "addRows": null,
        "draggable": null,
        "columns": [],
        "src": null,
        "text": null,
        "html": null
      },
]

export default addableComponents;